#!/usr/bin/env zsh
#
# Functions to offer "pretty" logging to the Console from various scripts in this repository.

info() {
  printf "\r  [ \033[00;34m🎉\033[0m ] $1\n"
}

processing() {
  printf "\r  [ \033[00;34m⏳\033[0m ] $1"
}

success() {
  printf "\r\033[2K  [ \033[00;32m👍\033[0m ] $1\n"
}

warning() {
  printf "\r\033[2K  [\033[0;33m🚧\033[0m] $1\n"
}

fail() {
  printf "\r\033[2K  [\033[0;31m🚨\033[0m] $1\n"
  echo ''
  exit 1
}
