#!/usr/bin/env zsh
#
# Functions that help with various scripts and templates in this repository.

type_exists() {
  if [ $(whence -p $1) ]; then
    return 0
  fi
  return 1
}

# Returns true if the current operating system is Linux.
is_linux() {
  [[ $(uname) == "Linux" ]]
}

# Returns true if the current operating system is macOS.
is_macos() {
  [[ $(uname) == "Darwin" ]]
}

# Determine if a command exists on the system.
is_cmd() {
  command -v $1 &>/dev/null
}

# Style the Terminal window
set_title() {
  case $TERM in
  xterm*)
    print -Pn "\e]2;${PWD:t}\a"
    ;;
  esac

  return 0
}
