# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "iina/homebrew-mpv-iina"
tap "microsoft/git"
tap "majd/repo", "https://github.com/majd/homebrew-repo.git"                            # ipatool
tap "peripheryapp/periphery", "https://github.com/peripheryapp/homebrew-periphery.git"  # periphery
tap "robotsandpencils/made", "https://github.com/RobotsAndPencils/homebrew-made.git"    # xcodes

# Settings
cask_args appdir: "/Applications"

cask "1password/tap/1password-cli"
brew "aria2"
brew "autojump"
brew "chezmoi"
brew "cloc"
brew "dockutil"
brew "duti"
brew "ffmpeg"
brew "gh"
brew "git"
cask "git-credential-manager-core"
brew "git-lfs"
brew "gnupg"
cask "ipatool"
brew "jq"
brew "less"
brew "mas"
brew "micro"
cask "periphery"
brew "pinentry-mac"
brew "pipx"
brew "poetry"
brew "pyenv"
brew "pyenv-virtualenv"
brew "sqlite"
brew "artginzburg/tap/sudo-touchid"
brew "swiftlint"
brew "wget"
brew "xcbeautify"
brew "XCTestHtmlReport/xchtmlreport/xchtmlreport"
brew "xcodes"
brew "zsh"

# Cask Apps
cask "1password"
cask "adobe-creative-suite"
cask "anki"
cask "arq"
cask "bartender"
cask "bbedit"
cask "choosy"
cask "dash"
cask "docker"
cask "downie"
cask "fastscripts"
cask "firefox"
cask "hazel"
cask "istat-menus"
brew "iina"
cask "iterm2"
cask "kaleidoscope"
cask "keyboard-maestro"
cask "launchcontrol"
cask "microsoft-edge"
cask "netnewswire"
cask "omnigraffle"
cask "openinterminal"
cask "paw"
cask "proxyman"
cask "rocket"
cask "permute"
cask "plistedit-pro"
cask "raycast"
cask "reveal"
cask "script-debugger"
cask "shottr"
cask "signal"
cask "subler"
cask "tableplus"
cask "tower"
cask "telegram"
cask "typora"
cask "transmit"
cask "unite"
cask "visual-studio-code"
cask "xcodes"
cask "zoom"

# Mac App Store
mas "1Blocker", id: 1365531024
mas "A Companion for SwiftUI", id: 1485436674
mas "Apple Configurator 2", id: 1037126344
mas "CARROT Weather", id: 993487541
mas "Channels Pro - IPTV Player", id: 1552284117
mas "Codeshot", id: 1541665460
mas "Core Data Lab", id: 1460684638
mas "Craft", id: 1487937127
mas "Darkroom: Photo & Video Editor", id: 953286746
mas "Day One", id: 1055511498
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "Easy CSV Editor", id: 1171346381
mas "Expressions", id: 913158085
mas "Focus - Time Management", id: 777233759
mas "Home Assistant", id: 1099568401
mas "HomePass for HomeKit", id: 1330266650
mas "Hush Nag Blocker", id: 1544743900
mas "Infuse 7", id: 1136220934
mas "JSON Editor", id: 567740330
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "Mate", id: 1005088137
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "OmniOutliner", id: 1142578772
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel - Delivery Tracking", id: 639968404
mas "PCalc", id: 403504866
mas "PLIST Editor", id: 1157491961
mas "PDF Expert", id: 1055273043
mas "PocketTube for Safari", id: 1533703891
mas "Renamer 6", id: 1460229011
mas "Save to Upnext", id: 1583423832
mas "Screens", id: 1224268771
mas "Slack", id: 803453959
mas "Sourcery Pro", id: 1561780836
mas "Soulver 3", id: 1508732804
mas "Tailscale", id: 1475387142
mas "Transloader", id: 572281534
mas "Tweaks for Twitter", id: 1567751529
mas "UserScripts", id: 1463298887
mas "xScope", id: 889428659

# Not supported by Homebrew (yet)
# SD Notary - https://latenightsw.com/sd-notary-notarizing-made-easy/
# Opal - https://opalcamera.com

# Fonts
# Apple / iOS https://developer.apple.com/fonts/
cask "font-new-york"
cask "font-sf-compact"
cask "font-sf-pro"
cask "font-sf-arabic"
cask "font-sf-mono"
