# Taps
tap "majd/repo", "https://github.com/majd/homebrew-repo.git"                            # ipatool
tap "peripheryapp/periphery", "https://github.com/peripheryapp/homebrew-periphery.git"  # periphery
tap "buo/cask-upgrade"

# Settings
cask_args appdir: "/Applications"

# Cask Apps
cask "1password"
cask "adobe-creative-cloud"
cask "bbedit"
cask "chatgpt"
cask "claude"
cask "cleanshot"
cask "dash"
cask "downie"
cask "fastscripts"
cask "firefox"
cask "github-copilot-for-xcode"
cask "hazel"
cask "istat-menus"
cask "iina"
cask "iterm2"
cask "itermai"
cask "jordanbaird-ice"
cask "kaleidoscope"
cask "keyboard-maestro"
cask "launchcontrol"
cask "mullvad-vpn"
cask "netnewswire"
cask "orbstack"
cask "omnigraffle"
cask "openinterminal"
cask "rapidapi"
cask "proxyman"
cask "permute"
cask "plistedit-pro"
cask "raycast"
cask "screens-connect"
cask "script-debugger"
cask "signal"
cask "subler"
cask "syntax-highlight"
cask "tableplus"
cask "tower"
cask "typora"
cask "transmit"
cask "virtualbuddy"
cask "visual-studio-code"
cask "xcodes"
cask "zoom"

# Not supported by Homebrew (yet)
# SD Notary - https://latenightsw.com/sd-notary-notarizing-made-easy/
# Opal - https://opalcamera.com
