 {{- $refreshPeriodDay := "24h" -}}
 {{- $refreshPeriodWeek := "168h" -}}

.vim/pack/jww/start/editorconfig-vim:
  type: git-repo
  url: https://github.com/editorconfig/editorconfig-vim.git
  refreshPeriod: {{ $refreshPeriodWeek }}

.config/zsh/functions/_docker-compose:
  type: file
  url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose
  refreshPeriod: {{ $refreshPeriodWeek }}

.config/zsh/functions/_docker:
  type: file
  url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
  refreshPeriod: {{ $refreshPeriodWeek }}

{{ if .pff }}
.config/zsh/functions/_asdf:
  type: file
  url: https://raw.githubusercontent.com/asdf-vm/asdf/master/completions/_asdf
  refreshPeriod: {{ $refreshPeriodWeek }}
{{ end }}

.cache/zsh/external/zsh-syntax-highlighting:
  type: archive
  url: https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriodWeek }}

.cache/zsh/external/zsh-autosuggestions:
  type: git-repo
  url: https://github.com/zsh-users/zsh-autosuggestions
  exact: true
  refreshPeriod: {{ $refreshPeriodWeek }}

{{ if eq .chezmoi.os "darwin" }}
.local/share/xcode/lldb-scripts:
  type: git-repo
  url: https://github.com/DerekSelander/LLDB.git
  refreshPeriod: {{ $refreshPeriodWeek }}
  include: ["lldb_commands"]

.cache/iterm2/iterm2_shell_integration.zsh:
  type: file
  url: https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.zsh
  refreshPeriod: {{ $refreshPeriodWeek }}
{{ end }}
