{{- $refreshPeriodDay := "24h" -}}
{{- $refreshPeriodWeek := "168h" -}}

# ==================================================
# ZSH Plugins and autocompletions
# ==================================================

.config/zsh/functions/_docker-compose:
  type: file
  url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose
  refreshPeriod: {{ $refreshPeriodWeek }}

.config/zsh/functions/_docker:
  type: file
  url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
  refreshPeriod: {{ $refreshPeriodWeek }}

.config/zsh/functions/_eza:
  type: git-repo
  url: https://github.com/eza-community/eza.git
  refreshPeriod: {{ $refreshPeriodWeek }}

.cache/zsh/external/zsh-syntax-highlighting:
  type: archive
  url: https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriodWeek }}

.cache/zsh/external/zsh-autocomplete:
  type: git-repo
  url: https://github.com/marlonrichert/zsh-autocomplete
  exact: true
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriodWeek }}

{{ if not .synology }}
.cache/zsh/external/zsh-autosuggestions:
  type: git-repo
  url: https://github.com/zsh-users/zsh-autosuggestions
  exact: true
  refreshPeriod: {{ $refreshPeriodWeek }}
{{ end }}

{{ if eq .chezmoi.os "darwin" }}
# ==================================================
# macOS Specific Submodules
# ==================================================

.local/share/xcode/lldb-scripts:
  type: git-repo
  url: https://github.com/DerekSelander/LLDB.git
  refreshPeriod: {{ $refreshPeriodWeek }}
  include: ["lldb_commands"]
{{ end }}

# ==================================================
# iTerm 2 Shell Integration
# ==================================================

.cache/iterm2/iterm2_shell_integration.zsh:
  type: file
  url: https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.zsh
  refreshPeriod: {{ $refreshPeriodWeek }}

# ==================================================
# VIM Plugins
# ==================================================

.local/share/pack/jww/start/zoxide.vim:
  type: git-repo
  url: https://github.com/nanotee/zoxide.vim.git
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/vim/pack/jww/opt/chezmoi.vim:
  type: git-repo
  url: https://github.com/alker0/chezmoi.vim.git
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/vim/pack/github/start/copilot.vim:
  type: git-repo
  url: https://github.com/github/copilot.vim.git
  refreshPeriod: {{ $refreshPeriodWeek }}
  pull:
    args: ["--depth=1"]
