 {{- $refreshPeriodDay := "24h" -}}
 {{- $refreshPeriodWeek := "168h" -}}

.vim/pack/jww/start/editorconfig-vim:
  type: git-repo
  url: https://github.com/editorconfig/editorconfig-vim.git
  refreshPeriod: {{ $refreshPeriodWeek }}

{{ if eq .chezmoi.os "darwin" }}
.local/share/xcode/lldb-scripts:
  type: git-repo
  url: https://github.com/DerekSelander/LLDB.git
  refreshPeriod: {{ $refreshPeriodWeek }}
  include: ["lldb_commands"]

.cache/iterm2/iterm2_shell_integration.zsh:
  type: file
  url: https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.zsh
  refreshPeriod: {{ $refreshPeriodWeek }}
{{ end }}
