name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/copilot-setup-steps.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/copilot-setup-steps.yml'

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v3
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
