name: ci

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'files/private_dot_config/zsh/**'
      - 'files/.chezmoi.*'
      - 'files/.chezmoi*/**'
      - 'install.sh'
      - '.install-password-manager.sh'
  pull_request:
    branches:
      - main

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
