name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      CODESPACES: true
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install chezmoi
        run: |
          ./install.sh

      - name: Verify installation and show versions
        run: |
          echo "=== System Information ==="
          uname -a
          echo ""
          echo "=== chezmoi ==="
          chezmoi --version
          echo ""
          echo "=== Project Dependencies ==="
          jq --version
          echo ""
          echo "=== Environment Setup Complete ==="
